### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR4all/OCR4all#129]
with this model and »Generate word level Page XML output«:

```
root@XXX:/.../ocr4all/models/custom# md5sum historical_french-2020-10-14/0/*
ecd83bdb5ddcc8965b8400cfb200a063  historical_french-2020-10-14/0/0.ckpt.h5
db6795bda982c04df343aa8c96379b9b  historical_french-2020-10-14/0/0.ckpt.json
bbc30499bb6a63652e960a6d392e0e5e  historical_french-2020-10-14/0/1.ckpt.h5
e7285ce37d8e1b0b42b4a5c63c8c3659  historical_french-2020-10-14/0/1.ckpt.json
996a92e0dab35f141b5ba303e3613b04  historical_french-2020-10-14/0/2.ckpt.h5
cf6efafd4f411140045cd8d4f36bdd80  historical_french-2020-10-14/0/2.ckpt.json
d76601ace7cb43c3cb8ed46a778de965  historical_french-2020-10-14/0/3.ckpt.h5
abdf36278fa976d4663e34952b692c01  historical_french-2020-10-14/0/3.ckpt.json
579419b364bff2f70975f35dac2ca95b  historical_french-2020-10-14/0/4.ckpt.h5
b787d4ab5ef9eb7e0f400a6fda78ddc5  historical_french-2020-10-14/0/4.ckpt.json
```
:
```
Traceback (most recent call last):
  File "/usr/local/bin/calamari-predict", line 33, in 
    sys.exit(load_entry_point('calamari-ocr==1.0.5', 'console_scripts', 'calamari-predict')())
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/scripts/predict.py", line 197, in main
    run(args)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/scripts/predict.py", line 120, in run
    dataset.store_text(prediction, sample, output_dir=output_dir, extension=args.extension)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py", line 353, in store_text
    self.store_words(prediction, sample)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py", line 316, in store_words
    words = self.get_words(prediction, sample)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/pagexml_dataset/dataset.py", line 283, in get_words
    words = [{"char": positions[0][0], "min_x": positions[0][1], "max_x": positions[0][2],
IndexError: list index out of range
Exception ignored in: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/input_dataset.py", line 356, in generator
TypeError: catching classes that do not inherit from BaseException is not allowed
Exception ignored in: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/predictor.py", line 280, in predict_dataset
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/input_dataset.py", line 311, in __exit__
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/input_dataset.py", line 155, in __exit__
  File "/usr/lib/python3.6/logging/__init__.py", line 1295, in debug
  File "/usr/lib/python3.6/logging/__init__.py", line 1548, in isEnabledFor
TypeError: '>=' not supported between instances of 'int' and 'NoneType'
```

**Comment by maxnth** [comment]
Will get by the next release which uses Calamari 2.x and uses its native word / glyph output option.

**Comment by maxnth** [comment]
Should be fixed in the latest OCR4all release which requires Calamari >=v2.x
