### ISSUE TITLE
kraken segmentation leads to OSError: Error reading file

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#135]
I've got a fresh installation of the new docker release (OCR4all: v0.6.0, LAREX: v0.7-RC1). When I try to run the Kraken segmentation, I see the following behaviour and the process flow stops.

**OUTPUT**
```
[5.5984] Segmenting /var/ocr4all/data/TEST/processing/0132.bin.png 
[5.5985] Segmenting /var/ocr4all/data/TEST/processing/0132.bin.png 
[12.2022] Vectorizing regions 
[12.4731] Vectorizing baselines 
```

**ERROR**
```
[14.8091] Failed processing /var/ocr4all/data/TEST/processing/0132.bin.png: ndim 
Traceback (most recent call last):
  File "/usr/local/bin/ocr4all-helper-scripts", line 8, in 
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ocr4all_helper_scripts/cli/kraken.py", line 12, in kraken_cli
    helper.postprocess()
  File "/usr/local/lib/python3.7/dist-packages/ocr4all_helper_scripts/helpers/kraken_helper.py", line 32, in postprocess
    root = etree.parse(str(xml)).getroot()
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1875, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1901, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/var/ocr4all/data/TEST/processing/0132.xml': failed to load external entity "/var/ocr4all/data/TEST/processing/0132.xml"
```

**Comment by maxnth** [comment]
Excuse the late reply. 
I just updated the Docker images `uniwuezpd/ocr4all:latest` and `uniwuezpd/ocr4all:0.6.1` to use the latest kraken version and also added exception handling for the error above to the [OCR4all_helper-scripts](https://github.com/OCR4all/OCR4all_helper-scripts) so that OCR4all shouldn't just abort the process in case kraken fails to create a result PAGE XML for a certain image.
