### ISSUE TITLE
OCR4ALL - CRITICAL error on recognition module 

### ISSUE THREAD

**Issue by sumofr** [OCR4all/OCR4all#154]
Hi

Got the following message on console error when starting recognition module in OCR4ALL:
Any help ?

 👍 CRITICAL 2023-03-30 15:59:24,164             tfaip.util.logging: Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/calamari-predict", line 8, in 
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/predict.py", line 188, in main
    run(args.root)
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/scripts/predict.py", line 120, in run
    predictor_params=args.predictor,
  File "/usr/local/lib/python3.7/dist-packages/calamari_ocr/ocr/predict/predictor.py", line 58, in from_paths
    predictor_args={"voter_params": voter_params},
  File "/usr/local/lib/python3.7/dist-packages/tfaip/predict/multimodelpredictor.py", line 96, in from_paths
    raise ValueError(f"The preprocessors differ {p.data.pre_proc} and {data_params.pre_proc}")
ValueError: The preprocessors differ SequentialProcessorPipelineParams(run_parallel=True, num_threads=-1, max_tasks_per_process=250, processors=[DataRangeProcessorParams(modes={, , }), CenterNormalizerProcessorParams(modes={, , }, extra_params=(4, 1.0, 0.3), line_height=48), FinalPreparationProcessorParams(modes={, , }, normalize=True, invert=True, transpose=True, pad=16, pad_value=False), AugmentationProcessorParams(modes={}, augmenter=DefaultDataAugmenterParams(), n_augmentations=0), TextNormalizerProcessorParams(modes={, , }, unicode_normalization='NFC'), TextRegularizerProcessorParams(modes={, , }, replacements=[Replacement(old='µ', new='μ', regex=False), Replacement(old='–——', new='-', regex=False), Replacement(old='–—', new='-', regex=False), Replacement(old='"', new="''", regex=False), Replacement(old='`', new="'", regex=False), Replacement(old='“', new="''", regex=False), Replacement(old='”', new="''", regex=False), Replacement(old='´', new="'", regex=False), Replacement(old='‘', new="'", regex=False), Replacement(old='’', new="'", regex=False), Replacement(old='“', new="''", regex=False), Replacement(old='”', new="''", regex=False), Replacement(old='“', new="''", regex=False), Replacement(old='„', new=',,', regex=False), Replacement(old='…', new='...', regex=False), Replacement(old='′', new="'", regex=False), Replacement(old='″', new="''", regex=False), Replacement(old='‴', new="'''", regex=False), Replacement(old='〃', new="''", regex=False), Replacement(old='Ⅰ', new='I', regex=False), Replacement(old='Ⅱ', new='II', regex=False), Replacement(old='Ⅲ', new='III', regex=False), Replacement(old='Ⅳ', new='IV', regex=False), Replacement(old='Ⅴ', new='V', regex=False), Replacement(old='Ⅵ', new='VI', regex=False), Replacement(old='Ⅶ', new='VII', regex=False), Replacement(old='Ⅷ', new='VIII', regex=False), Replacement(old='Ⅸ', new='IX', regex=False), Replacement(old='Ⅹ', new='X', regex=False), Replacement(old='Ⅺ', new='XI', regex=False), Replacement(old='Ⅻ', new='XII', regex=False), Replacement(old='Ⅼ', new='L', regex=False), Replacement(old='Ⅽ', new='C', regex=False), Replacement(old='Ⅾ', new='D', regex=False), Replacement(old='Ⅿ', new='M', regex=False), Replacement(old='ⅰ', new='i', regex=False), Replacement(old='ⅱ', new='ii', regex=False), Replacement(old='ⅲ', new='iii', regex=False), Replacement(old='ⅳ', new='iv', regex=False), Replacement(old='ⅴ', new='v', regex=False), Replacement(old='ⅵ', new='vi', regex=False), Replacement(old='ⅶ', new='vii', regex=False), Replacement(old='ⅷ', new='viii', regex=False), Replacement(old='ⅸ', new='ix', regex=False), Replacement(old='ⅹ', new='x', regex=False), Replacement(old='ⅺ', new='xi', regex=False), Replacement(old='ⅻ', new='xii', regex=False), Replacement(old='ⅼ', new='l', regex=False), Replacement(old='ⅽ', new='c', regex=False), Replacement(old='ⅾ', new='d', regex=False), Replacement(old='ⅿ', new='m', regex=False), Replacement(old='\\s+(?u)', new=' ', regex=True), Replacement(old='\\n(?u)', new='', regex=True), Replacement(old='^\\s+(?u)', new='', regex=True), Replacement(old='\\s+$(?u)', new='', regex=True)], rulesets=['spaces'], rulegroups=[]), StripTextProcessorParams(modes={, , }), PrepareSampleProcessorParams(modes={, , }, max_line_width=4096)]) and SequentialProcessorPipelineParams(run_parallel=True, num_threads=-1, max_tasks_per_process=250, processors=[CenterNormalizerProcessorParams(modes={, , }, extra_params=(4, 1.0, 0.3), line_height=48), FinalPreparationProcessorParams(modes={, , }, normalize=True, invert=True, transpose=True, pad=16, pad_value=0), BidiTextProcessorParams(modes={, , , }, bidi_direction=), StripTextProcessorParams(modes={, , , }), TextNormalizerProcessorParams(modes={, , , }, unicode_normalization='NFC'), TextRegularizerProcessorParams(modes={, , , }, replacements=[Replacement(old='(?u)\\s+', new=' ', regex=True), Replacement(old='(?u)\\n', new='', regex=True), Replacement(old='(?u)^\\s+', new='', regex=True), Replacement(old='(?u)\\s+$', new='', regex=True)], rulesets=['spaces'], rulegroups=[]), PrepareSampleProcessorParams(modes={, , }, max_line_width=4096)])

**Comment by sumofr** [comment]
Hello

You was right !! Too many models at the same time are provocking errors...
I solved my problem by using only the models of one type, and it's running
well now !!

Thanks for your answer !!!

Regards

Philippe Bezard-Falgas


Le mar. 18 avr. 2023 à 15:30, Maximilian Nöth ***@***.***> a
écrit :

**Comment by maxnth** [comment]
I'm glad that I was able to help.

In general it's fine to use multiple models, problems mostly arise when models in a recognition ensemble were trained with differente architectures (e. g. `deep3`) or with different pre-processors.
