### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/OCR4all#64]
Hello! During the recognition process the following error is thrown and the recognition effectively stops proceeding, while the Status still reads "Status: ERROR: The process is still running" (OCR4all ver 0.3.0, LAREX ver 0.3.1):

```
Process ForkProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/input_dataset.py", line 99, in run
    out = self.apply_single(*data)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/datasets/input_dataset.py", line 119, in apply_single
    line, params = self.params.data_processor.apply([line], 1, False)[0]
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 19, in apply
    processes=processes, progress_bar=progress_bar, max_tasks_per_child=max_tasks_per_child)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/utils/multiprocessing.py", line 32, in parallel_map
    out = list(map(f, d))
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/data_processing/data_preprocessor.py", line 50, in _apply_single
    data, params = proc._apply_single(data)
  File "/usr/local/lib/python3.6/dist-packages/calamari_ocr-1.0.5-py3.6.egg/calamari_ocr/ocr/data_processing/center_normalizer.py", line 15, in _apply_single
    out, params = self.normalize(data, cval=np.amax(data))
  File "<__array_function__ internals>", line 6, in amax
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

I have attached the PAGEXML and image files where the error occurs. I couldn't find anything suspicious here.

![0125 nrm](https://user-images.githubusercontent.com/52370148/85520619-7312f200-b603-11ea-816a-9820b1a0b427.png)
![0125 bin](https://user-images.githubusercontent.com/52370148/85520627-76a67900-b603-11ea-9eb4-4f4233a5a1c1.png)
[0125.txt](https://github.com/OCR4all/OCR4all/files/4824009/0125.txt)

**Comment by maxnth** [comment]
Hello, the problem is caused by the following faulty text-line in the PAGE XML which for some reason only has two coordinate points.
```xml
<TextLine id="l6">
    <Coords points="911,399 911,459"/>
    <TextEquiv>
        <Unicode/>
    </TextEquiv>
    <TextEquiv index="1">
        <Unicode>VANAMTatione fieri dicam Au-</Unicode>
    </TextEquiv>
</TextLine>
```
<details><summary>This can also be seen on the canvas</summary>
<p>
<img src="https://user-images.githubusercontent.com/33344081/85528662-7c548c80-b60c-11ea-81b8-64aeb62d875d.png"></img>
</p>
</details>

Was this PAGE XML created by using OCR4all only or were any changes done to the PAGE XML manually?

**Comment by alexander-winkler** [comment]
Oh, great, thank you! Maybe it's useful for you to know that the pagexml is the result of the new function that converts legacy data into pagexml.

**Comment by maxnth** [comment]
> Oh, great, thank you! Maybe it's useful for you to know that the pagexml is the result of the new function that converts legacy data into pagexml.

That's actually pretty useful, thank you.
Would it be possible for you to send us the legacy project (or all legacy files related to page `0125` in case the project is very large)?

**Comment by alexander-winkler** [comment]
I hope this helps ..

[0125.zip](https://github.com/OCR4all/OCR4all/files/4824529/0125.zip)

**Comment by maxnth** [comment]
Thank you for the files.
I sadly couldn't reproduce the broken coordinates when converting to latest with the supplied legacy files but we'll keep looking into this issue.
