### ISSUE TITLE
Line segmentation with TextRegion (no subtype)

### ISSUE THREAD

**Issue by b2m** [OCR4all/OCR4all#92]
When using `TextRegion` (no subtype) I receive the following error when performing line segmentation.

**Console Output:**
```
Process 1 images, with 1 in parallel
Start process for '0001.bin'
        |- Image: '/data/processing/0001.bin.png'
        |- Annotations: '/data/processing/0001.xml' 
[0001.bin] Retrieve TextRegions
[0001.bin] Extract Textlines from TextRegions
[0001.bin] Skew estimate between +/-2.0 in 8 steps. Estimated -0.0°
[0001.bin] Skew estimate between +/-2.0 in 8 steps. Estimated -0.0°
[0001.bin] Generate new PAGE xml with textlines
Save annotations into '/data/processing/0001.xml'
Process 1 images, with 2 in parallel
Start process for '0001.bin'
        |- Image: '/data/processing/0001.bin.png'
        |- Annotations: '/data/processing/0001.xml' 
[0001.bin] Retrieve TextRegions
```

**Console Error:**
```
Traceback (most recent call last):
  File "/usr/local/bin/pagelineseg", line 33, in 
    sys.exit(load_entry_point('ocr4all-helpers==0.2.2', 'console_scripts', 'pagelineseg')())
  File "/usr/local/lib/python3.6/dist-packages/ocr4all_helpers-0.2.2-py3.6.egg/ocr4all_helpers/pagelineseg.py", line 634, in cli
    pool.map(parallel, dataset)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.6/dist-packages/ocr4all_helpers-0.2.2-py3.6.egg/ocr4all_helpers/pagelineseg.py", line 625, in parallel
    remove_images=args.remove_images)
  File "/usr/local/lib/python3.6/dist-packages/ocr4all_helpers-0.2.2-py3.6.egg/ocr4all_helpers/pagelineseg.py", line 322, in pagexmllineseg
    coordmap[rid] = {"type": r.attrib["type"]}
  File "src/lxml/etree.pyx", line 2479, in lxml.etree._Attrib.__getitem__
KeyError: 'type'
```

**Expectation**: I would expect to be allowed using  `TextRegion` without an explicit subtype (such as `paragraph` or `heading`).

**Version:** OCR4All was used via docker and the current ls6uniwue/ocr4all:**latest**.

**Related:**
 - OCR4all/LAREX#224

**Comment by maxnth** [comment]
I just updated the corresponding script in [OCR4all_helper-scripts](https://github.com/OCR4all/OCR4all_helper-scripts) and line segmentation should now also run for `TextRegion` elements without any specified sub-type. 
The fix will be available in the upcoming release of the Docker image.

**Comment by b2m** [comment]
I was trying to reproduce the described error using the current ls6uniwue/ocr4all:**nightly** docker image containing
 - OCR4All: 0.5-RC2
 - Larex: 0.5-RC3

As described the reported bug is no longer reproducible, and therefore fixed.

Thank you =)
